const SECTION_NAME = "Knowledge of Capital Markets";

function q(section_id, topic, difficulty, prompt, choices, correct, explanation, tags, objective, tip) {
  return {
    section_id, section_name: SECTION_NAME, topic, difficulty, prompt,
    choices: { A: choices[0], B: choices[1], C: choices[2], D: choices[3] },
    correct_answer: correct, explanation, keyword_tags: tags,
    learning_objective: objective, remediation_tip: tip,
  };
}

function section1_questions() {
  const items = [];

    items.push(q(1, "equity securities", "easy",
        "An investor purchases 200 shares of XYZ common stock at $45 per share. If XYZ pays a quarterly dividend of $0.50 per share, how much dividend income will the investor receive each quarter?",
        ["$50", "$100", "$200", "$400"], "B",
        "Quarterly dividend = shares × dividend per share = 200 × $0.50 = $100.",
        ["dividends", "common stock", "equity securities"],
        "Calculate dividend income from common stock holdings",
        "Practice multiplying shares outstanding by per-share dividends for quarterly and annual income."))
    items.push(q(1, "equity securities", "medium",
        "A board of directors declares a 3-for-2 stock split. An investor who owns 100 shares at $60 per share will after the split own:",
        ["100 shares valued at approximately $60 each", "150 shares valued at approximately $40 each", "200 shares valued at approximately $30 each", "50 shares valued at approximately $120 each"], "B",
        "A 3-for-2 split increases shares by 50% (100 → 150) and reduces price proportionally ($60 × 100/150 = $40). Total market value stays roughly the same.",
        ["stock split", "equity securities", "shareholder equity"],
        "Understand how stock splits affect share count and price",
        "Remember: splits change the number of shares and per-share price but not total position value."))
    items.push(q(1, "equity securities", "medium",
        "Which right is typically available to common stockholders but NOT to preferred stockholders?",
        ["Priority claim on assets at liquidation", "Fixed dividend payments", "Voting on major corporate matters such as mergers", "Preference over common in dividend payments"], "C",
        "Common stockholders generally receive voting rights. Preferred stockholders usually have dividend and liquidation priority but limited or no voting rights.",
        ["voting rights", "common stock", "preferred stock"],
        "Distinguish common vs preferred stockholder rights",
        "Create a side-by-side chart of common and preferred features before exam day."))
    items.push(q(1, "equity securities", "hard",
        "A corporation issues cumulative preferred stock with a $4 annual dividend. No dividends were paid for two years. In year three, the board declares a $5 per share dividend on common stock. How much must cumulative preferred shareholders receive per share before common receives anything?",
        ["$4", "$5", "$8", "$12"], "D",
        "Cumulative preferred must receive all missed dividends ($4 × 2 = $8) plus the current year's $4 preferred dividend = $12, before common shareholders receive the declared dividend.",
        ["cumulative preferred", "dividends", "equity securities"],
        "Apply cumulative preferred dividend arrearage rules",
        "Work through multi-year dividend scenarios with missed payments on cumulative preferred."))
    items.push(q(1, "equity securities", "easy",
        "American Depositary Receipts (ADRs) allow U.S. investors to:",
        ["Purchase foreign securities denominated and traded in U.S. dollars on U.S. exchanges", "Avoid all currency exchange risk permanently", "Receive FDIC insurance on international stocks", "Trade municipal bonds on foreign exchanges"], "A",
        "ADRs represent ownership in foreign companies and trade in U.S. markets in dollars, simplifying access to non-U.S. equities.",
        ["ADR", "foreign securities", "equity securities"],
        "Explain the purpose of ADRs for U.S. investors",
        "Note that ADRs still carry currency and foreign market risk despite dollar-denominated trading."))
    items.push(q(1, "equity securities", "medium",
        "A customer asks why growth stocks often pay low or no dividends. The BEST explanation is that these companies:",
        ["Are prohibited by the SEC from paying dividends", "Reinvest earnings to fund expansion rather than distribute them", "Must pay dividends only to institutional investors", "Pay dividends only after 10 years of profitability"], "B",
        "Growth companies typically retain earnings to finance expansion, acquisitions, or R&D instead of distributing large dividends.",
        ["growth stock", "retained earnings", "equity securities"],
        "Explain growth stock dividend characteristics",
        "Contrast growth (low payout) vs value (higher yield) investment approaches."))
    items.push(q(1, "equity securities", "hard",
        "Warrants are LEAST similar to which of the following?",
        ["Long-term call options issued by the company", "Rights offerings to existing shareholders", "Convertible bond conversion privileges", "Put options purchased on an exchange"], "D",
        "Warrants give the right to buy stock from the company at a set price, similar to calls and rights. Standard exchange-traded puts grant the right to sell, which is the opposite economic position.",
        ["warrants", "options basics", "equity securities"],
        "Compare warrants to rights and options",
        "Review who issues warrants (company) vs exchange-traded options (OCC)."))
    items.push(q(1, "equity securities", "easy",
        "Treasury stock on a corporation's balance sheet represents:",
        ["Shares the company has repurchased and holds in its own treasury", "U.S. Treasury bonds held as investments", "Stock pledged as loan collateral by shareholders", "Shares held by the Federal Reserve"], "A",
        "Treasury stock is previously issued shares reacquired by the issuing corporation, reducing shares outstanding in the market.",
        ["treasury stock", "share repurchase", "equity securities"],
        "Define treasury stock and its effect on outstanding shares",
        "Connect share buybacks to EPS impact and reduced float."))
    items.push(q(1, "equity securities", "medium",
        "A rights offering gives existing shareholders the opportunity to:",
        ["Sell their shares back to the company at a premium", "Maintain proportional ownership by purchasing additional shares, often at a discount", "Convert common stock to bonds automatically", "Vote on Federal Reserve policy"], "B",
        "Rights offerings allow current owners to buy more shares (usually at a discount) to avoid dilution when the company issues new stock.",
        ["rights offering", "dilution", "primary market"],
        "Understand rights offerings and anti-dilution purpose",
        "Trace how exercising rights preserves ownership percentage in a new issue."))
    items.push(q(1, "equity securities", "hard",
        "If a company undergoes bankruptcy liquidation, the order of claims is generally:",
        ["Common stockholders, preferred stockholders, bondholders", "Bondholders, preferred stockholders, common stockholders", "Preferred stockholders, common stockholders, bondholders", "All equity holders share equally with creditors"], "B",
        "In liquidation, secured creditors and bondholders are paid before preferred shareholders, who are paid before common shareholders.",
        ["liquidation priority", "capital structure", "equity securities"],
        "Recall priority of claims in corporate liquidation",
        "Memorize the hierarchy: debt → preferred → common."))

    items.push(q(1, "debt securities", "medium",
        "A corporate bond with a $1,000 par value and 6% coupon pays annual interest of:",
        ["$6", "$60", "$600", "$1,060"], "B",
        "Annual coupon = par × coupon rate = $1,000 × 6% = $60.",
        ["coupon", "debt securities", "bond interest"],
        "Calculate annual coupon payments on bonds",
        "Practice converting coupon rates to dollar amounts using par value."))
    items.push(q(1, "debt securities", "hard",
        "A $1,000 par bond with a 5% coupon is purchased at $900. The approximate current yield is:",
        ["4.5%", "5.0%", "5.56%", "6.25%"], "C",
        "Current yield = annual coupon / market price = $50 / $900 ≈ 5.56%.",
        ["current yield", "debt securities", "bond calculations"],
        "Compute current yield when a bond trades at a discount",
        "Distinguish current yield from yield to maturity and nominal yield."))
    items.push(q(1, "debt securities", "medium",
        "When interest rates in the market rise, the price of an existing fixed-rate bond will most likely:",
        ["Increase", "Decrease", "Remain unchanged", "Become equal to par regardless of coupon"], "B",
        "Bond prices and interest rates move inversely. Higher rates make existing lower-coupon bonds less attractive, pushing prices down.",
        ["interest rate risk", "yield and bond price relationship", "debt securities"],
        "Explain the inverse relationship between bond prices and interest rates",
        "Use a simple example: a 4% bond vs new 6% bonds when rates rise."))
    items.push(q(1, "debt securities", "easy",
        "A bond trading at a premium most likely has a coupon rate that is:",
        ["Below current market interest rates", "Above current market interest rates", "Equal to zero", "Unrelated to market rates"], "B",
        "Investors pay above par for bonds paying more than prevailing rates, creating a premium price.",
        ["premium bond", "coupon rate", "debt securities"],
        "Relate premium/discount pricing to coupon vs market rates",
        "If coupon > market rate → premium; coupon < market rate → discount."))
    items.push(q(1, "debt securities", "hard",
        "An investor buys a 10-year corporate bond at par. Two years later, the issuer's credit rating is downgraded. The bond's price will most likely:",
        ["Rise due to higher demand", "Fall due to increased credit risk", "Stay at par because maturity is unchanged", "Convert automatically to preferred stock"], "B",
        "Credit downgrades increase default risk perception, typically lowering bond prices (raising yields).",
        ["credit risk", "bond ratings", "debt securities"],
        "Understand how credit quality changes affect bond prices",
        "Review investment grade vs high-yield (junk) bond risk profiles."))
    items.push(q(1, "debt securities", "medium",
        "Convertible bonds allow the holder to:",
        ["Convert bond interest into tax credits", "Exchange the bond for a fixed number of common shares", "Convert the bond to a municipal security", "Avoid all interest rate risk"], "B",
        "Convertible bonds include an embedded option to convert into common stock at a predetermined ratio.",
        ["convertible bonds", "hybrid securities", "debt securities"],
        "Describe convertible bond features and investor appeal",
        "Note convertibles offer equity upside with bond downside protection (relative to stock)."))
    items.push(q(1, "debt securities", "easy",
        "The nominal (coupon) yield of a bond is calculated using:",
        ["Market price and annual interest", "Par value and annual coupon payment", "Yield to maturity only", "The bond's credit rating"], "B",
        "Nominal yield = annual coupon / par value, regardless of current market price.",
        ["nominal yield", "coupon yield", "debt securities"],
        "Define nominal yield vs current yield and YTM",
        "Calculate all three yields on the same bond to see the differences."))
    items.push(q(1, "debt securities", "medium",
        "A zero-coupon bond is characterized by:",
        ["No credit risk because it is government-backed only", "No periodic interest payments; return comes from discount to par at maturity", "A variable coupon tied to LIBOR", "Automatic conversion to equity at maturity"], "B",
        "Zero-coupon bonds are sold at a deep discount and pay par at maturity; there are no interim coupon payments.",
        ["zero-coupon bond", "discount bond", "debt securities"],
        "Identify zero-coupon bond payment structure",
        "Remember zeros have high interest rate sensitivity (long duration effect)."))
    items.push(q(1, "debt securities", "hard",
        "A bond with a 7% coupon purchased at $1,050 has a current yield that is:",
        ["Greater than 7%", "Equal to 7%", "Less than 7%", "Impossible to determine without maturity date"], "C",
        "Current yield = $70 / $1,050 ≈ 6.67%, which is less than the 7% coupon because the bond was bought at a premium.",
        ["current yield", "premium bond", "debt securities"],
        "Compare coupon rate to current yield at premium prices",
        "Premium → current yield < coupon; discount → current yield > coupon."))
    items.push(q(1, "debt securities", "medium",
        "Debentures are corporate bonds that are:",
        ["Secured by specific company assets", "Unsecured, backed only by the issuer's general creditworthiness", "Guaranteed by the FDIC", "Issued only by municipalities"], "B",
        "Debentures are unsecured debt obligations relying on the issuer's overall financial strength.",
        ["debentures", "unsecured debt", "debt securities"],
        "Distinguish secured bonds from debentures",
        "Secured bonds have collateral; debentures do not."))

    items.push(q(1, "municipal bonds", "medium",
        "General obligation (GO) municipal bonds are backed primarily by:",
        ["Revenue from toll roads and airports only", "The issuer's taxing power", "Federal government guarantees", "Corporate earnings pledges"], "B",
        "GO bonds are secured by the municipality's ability to levy taxes, not by a specific project's revenue.",
        ["GO bonds", "municipal bonds", "tax backing"],
        "Differentiate GO bonds from revenue bonds",
        "GO = full faith and credit/taxing power; revenue = project income."))
    items.push(q(1, "municipal bonds", "medium",
        "Revenue bonds are repaid from:",
        ["Unlimited ad valorem property taxes", "Income generated by the specific facility or project", "Federal matching grants only", "Sales of common stock"], "B",
        "Revenue bondholders depend on tolls, fees, rents, or other project-specific income streams.",
        ["revenue bonds", "municipal bonds", "project finance"],
        "Identify revenue sources backing revenue bonds",
        "Assess project feasibility when evaluating revenue bond credit quality."))
    items.push(q(1, "municipal bonds", "easy",
        "Interest on most municipal bonds issued for governmental purposes is generally:",
        ["Fully taxable at federal and state levels", "Exempt from federal income tax", "Taxable only to non-residents", "Subject to capital gains treatment only"], "B",
        "Most muni interest is federally tax-exempt, a key benefit for investors in higher tax brackets.",
        ["tax-exempt interest", "municipal bonds", "tax considerations"],
        "Know basic federal tax treatment of municipal bond interest",
        "Review exceptions: private activity bonds may trigger AMT."))
    items.push(q(1, "municipal bonds", "hard",
        "A wealthy investor in the 37% federal bracket compares a 4% corporate bond to a 3% municipal bond. The taxable-equivalent yield of the muni is approximately:",
        ["3.0%", "4.0%", "6.35%", "4.76%"], "D",
        "Taxable-equivalent yield = muni yield / (1 - tax rate) = 3% / 0.63 ≈ 4.76%.",
        ["taxable-equivalent yield", "municipal bonds", "tax considerations"],
        "Calculate taxable-equivalent yield for muni comparison",
        "Use TEY formula when comparing taxable and tax-exempt bonds."))
    items.push(q(1, "municipal bonds", "medium",
        "Which statement about municipal bond insurance is TRUE?",
        ["Insurance guarantees the bond will never default on principal or interest", "Insurance enhances credit quality but does not eliminate all risks", "Insurance converts the bond to a U.S. Treasury security", "Insurance is required for all municipal issuances"], "B",
        "Bond insurance improves credit ratings and marketability but insured bonds can still face risks such as liquidity issues or insurer downgrade.",
        ["municipal bond insurance", "credit enhancement", "municipal bonds"],
        "Understand role and limits of muni bond insurance",
        "Insurance covers issuer default risk through the insurer's guarantee."))
    items.push(q(1, "municipal bonds", "easy",
        "A municipal issuer publishes an official statement before a new bond offering. This document is most similar to a:",
        ["Corporate prospectus in the primary market", "Broker-dealer Form U4", "Currency Transaction Report", "Margin account agreement"], "A",
        "The official statement discloses terms, financial condition, and risks for a new muni issue, similar to a corporate prospectus.",
        ["official statement", "municipal bonds", "primary market"],
        "Identify key disclosure documents for municipal offerings",
        "Find continuing disclosure documents on EMMA for ongoing muni information."))
    items.push(q(1, "municipal bonds", "hard",
        "Interest from certain private activity municipal bonds may be subject to:",
        ["Only state estate taxes", "The alternative minimum tax (AMT)", "SEC registration fees", "FINRA arbitration assessments"], "B",
        "Private activity bond interest can be a preference item for AMT, affecting some investors.",
        ["AMT", "private activity bonds", "municipal bonds"],
        "Recognize AMT implications for certain municipal bonds",
        "Ask high-income clients about AMT exposure when recommending private activity munis."))
    items.push(q(1, "municipal bonds", "medium",
        "Industrial development revenue bonds (IDRBs) are typically:",
        ["General obligation bonds backed by unlimited taxes", "Revenue bonds financing private business facilities", "U.S. Treasury inflation-protected securities", "Agency pass-through securities"], "B",
        "IDRBs are revenue bonds where a municipality issues on behalf of a private entity; repayment depends on the project's success.",
        ["IDRB", "revenue bonds", "municipal bonds"],
        "Classify IDRBs within municipal bond categories",
        "IDRBs carry project/business risk in addition to typical muni considerations."))

    items.push(q(1, "treasuries", "easy",
        "U.S. Treasury bills (T-bills) are issued:",
        ["At par with semiannual coupon payments", "At a discount to par with no periodic interest payments", "Only to foreign governments", "With maturities of 15 to 30 years"], "B",
        "T-bills are short-term discount securities maturing in one year or less, with return equal to the difference between purchase price and par.",
        ["T-bills", "treasuries", "discount securities"],
        "Describe T-bill issuance and payment structure",
        "Memorize Treasury maturity categories: bills, notes, bonds."))
    items.push(q(1, "treasuries", "medium",
        "U.S. Treasury notes typically have maturities of:",
        ["4 weeks to 52 weeks", "2 to 10 years", "20 to 30 years only", "More than 30 years"], "B",
        "Treasury notes range from 2 to 10 years, paying semiannual interest.",
        ["Treasury notes", "treasuries", "government securities"],
        "Match Treasury security types to maturity ranges",
        "Bills < 1 year; notes 2-10 years; bonds 20-30 years."))
    items.push(q(1, "treasuries", "medium",
        "Treasury Inflation-Protected Securities (TIPS) protect investors against:",
        ["Credit default by the U.S. government", "Inflation eroding purchasing power", "Stock market volatility", "State income taxes only"], "B",
        "TIPS principal adjusts with CPI changes, helping preserve real purchasing power.",
        ["TIPS", "inflation protection", "treasuries"],
        "Explain how TIPS adjust for inflation",
        "Compare nominal Treasuries vs TIPS in rising inflation environments."))
    items.push(q(1, "treasuries", "hard",
        "STRIPS are created when:",
        ["The Treasury issues new preferred stock", "Coupon and principal payments of Treasury securities are separated and sold as zero-coupon instruments", "Municipal bonds are federally guaranteed", "Agency MBS are pooled for trading"], "B",
        "STRIPS (Separate Trading of Registered Interest and Principal Securities) are zero-coupon Treasuries created by separating coupons from principal.",
        ["STRIPS", "zero-coupon", "treasuries"],
        "Understand STRIPS structure and zero-coupon nature",
        "STRIPS have no reinvestment risk for coupons since there are no interim payments."))
    items.push(q(1, "treasuries", "easy",
        "Interest income on U.S. Treasury securities is:",
        ["Exempt from federal income tax", "Taxable at the federal level but exempt from state and local income taxes", "Exempt from all U.S. taxes", "Taxed only as capital gains"], "B",
        "Treasury interest is subject to federal income tax but generally exempt from state and local income taxes.",
        ["Treasury taxation", "treasuries", "tax considerations"],
        "Know federal vs state tax treatment of Treasuries",
        "Contrast Treasury tax treatment with municipal bond interest."))
    items.push(q(1, "treasuries", "medium",
        "In the secondary market, U.S. Treasury securities are considered highly liquid primarily because:",
        ["They are insured by FINRA", "They have large trading volume and active dealer participation", "They cannot be sold before maturity", "They are not subject to interest rate risk"], "B",
        "Deep markets and widespread dealer activity make Treasuries among the most liquid securities.",
        ["liquidity", "treasuries", "secondary market"],
        "Explain Treasury market liquidity characteristics",
        "Liquidity does not eliminate interest rate or inflation risk."))

    items.push(q(1, "agency securities", "medium",
        "Agency securities are issued by:",
        ["The U.S. Treasury Department exclusively", "Government-sponsored enterprises and certain federal agencies", "Individual state treasurers only", "Municipal housing authorities without federal ties"], "B",
        "Agencies like Fannie Mae, Freddie Mac, and FHLB issue debt; some carry explicit government backing while GSEs have implicit support.",
        ["agency securities", "GSE", "Fannie Mae"],
        "Identify issuers of agency securities",
        "Distinguish fully guaranteed agency debt from GSE obligations."))
    items.push(q(1, "agency securities", "hard",
        "Mortgage pass-through securities issued by GSEs expose investors to prepayment risk because:",
        ["Homeowners may refinance or pay off mortgages early when rates fall", "The SEC can call the securities at any time", "Agency debt is always zero-coupon", "Prepayment eliminates all credit risk permanently"], "A",
        "Falling rates often trigger refinancing, returning principal sooner than expected and forcing reinvestment at lower rates.",
        ["prepayment risk", "MBS", "agency securities"],
        "Understand prepayment risk in mortgage-backed securities",
        "Prepayment risk hurts investors when rates decline; extension risk can occur when rates rise."))
    items.push(q(1, "agency securities", "easy",
        "Compared to U.S. Treasury bonds of similar maturity, agency securities generally offer:",
        ["Lower yields because they are risk-free", "Slightly higher yields to compensate for somewhat greater credit risk", "Identical yields in all market conditions", "No secondary market trading"], "B",
        "Agencies (especially GSEs) typically yield more than Treasuries due to marginally higher perceived credit risk.",
        ["agency yield spread", "agency securities", "credit risk"],
        "Compare agency and Treasury yield relationships",
        "Higher yield often signals slightly higher risk—not a free lunch."))
    items.push(q(1, "agency securities", "medium",
        "GNMA (Ginnie Mae) pass-through securities are backed by:",
        ["The full faith and credit of the U.S. government", "Corporate bond covenants only", "State tax revenues", "FDIC deposit insurance"], "A",
        "Ginnie Mae securities are the only mortgage-backed securities with explicit U.S. government backing.",
        ["GNMA", "agency securities", "government guarantee"],
        "Distinguish GNMA from Fannie Mae and Freddie Mac credit support",
        "GNMA = explicit government guarantee; GSE MBS = implicit backing historically."))

    items.push(q(1, "primary market", "easy",
        "The primary market is where:",
        ["Investors trade existing securities with each other", "New securities are sold by issuers to investors", "Only short sales occur", "The Federal Reserve conducts open market operations exclusively"], "B",
        "The primary market handles new issues—IPOs, secondary offerings, and bond issuances sold by the issuer.",
        ["primary market", "new issues", "underwriting"],
        "Define primary market function",
        "Trace money flow: investor → underwriter → issuer in primary transactions."))
    items.push(q(1, "secondary market", "easy",
        "Which activity occurs in the secondary market?",
        ["An IPO of newly issued common stock", "A pension fund buying previously issued shares from another investor", "A municipality selling bonds for the first time", "A company filing a registration statement with the SEC"], "B",
        "Secondary market transactions involve trading of already-issued securities between investors.",
        ["secondary market", "liquidity", "trading"],
        "Identify secondary market transactions",
        "Secondary trading provides liquidity but does not raise capital for the issuer."))
    items.push(q(1, "underwriting", "medium",
        "In a firm commitment underwriting, the underwriter:",
        ["Acts solely as agent with no inventory risk", "Purchases the entire issue from the issuer and resells to the public", "Guarantees only best-efforts marketing", "Sets the Federal Funds rate"], "B",
        "Firm commitment means the underwriter buys the issue, assuming the risk of reselling at a profit or loss.",
        ["firm commitment", "underwriting", "investment banking"],
        "Compare firm commitment vs best efforts underwriting",
        "Firm commitment = principal risk; best efforts = agent selling on behalf of issuer."))
    items.push(q(1, "underwriting", "medium",
        "In a best efforts underwriting, the underwriter:",
        ["Must purchase all unsold shares from the issuer", "Acts as agent, selling as much as possible without guaranteeing the full issue", "Is exempt from SEC registration requirements", "Sets the coupon rate on Treasury bonds"], "B",
        "Best efforts underwriters sell on an agency basis; unsold securities may be retained by the issuer.",
        ["best efforts", "underwriting", "primary market"],
        "Describe best efforts underwriting arrangement",
        "Best efforts is common for riskier or smaller offerings."))
    items.push(q(1, "underwriting", "hard",
        "During an IPO cooling-off period, which activity is permitted?",
        ["Sales of the new security to the public", "Distribution of a preliminary prospectus (red herring)", "Immediate trading on the secondary market", "Guaranteed allocation to all interested investors"], "B",
        "The cooling-off period allows distribution of the preliminary prospectus but prohibits sales until the registration is effective.",
        ["cooling-off period", "red herring", "IPO"],
        "Understand IPO timeline restrictions during cooling-off",
        "Final prospectus is delivered at or before confirmation of sale."))
    items.push(q(1, "primary market", "medium",
        "A shelf registration allows an issuer to:",
        ["Avoid all SEC disclosure requirements", "Register securities in advance and offer them over a multi-year period as market conditions warrant", "Sell securities only to employees", "Trade exclusively on foreign exchanges"], "B",
        "Shelf registrations let qualifying issuers register securities once and bring them to market incrementally.",
        ["shelf registration", "primary market", "SEC registration"],
        "Explain shelf registration convenience for issuers",
        "Shelf offerings still require prospectus supplements for each takedown."))
    items.push(q(1, "secondary market", "medium",
        "The over-the-counter (OTC) market is BEST described as:",
        ["A single physical exchange in New York City", "A network of broker-dealers trading securities not listed on a major exchange", "A market where only U.S. Treasuries trade", "A primary market for IPOs only"], "B",
        "OTC trading occurs through dealer networks for unlisted or thinly traded securities, including many bonds and penny stocks.",
        ["OTC market", "secondary market", "broker-dealers"],
        "Describe OTC market structure",
        "NASDAQ is an electronic OTC market for many equity securities."))
    items.push(q(1, "underwriting", "hard",
        "An all-or-none (AON) underwriting stipulates that:",
        ["The underwriter may sell shares partially and keep the rest", "The entire issue must be sold or the offering is canceled", "Investors may buy any fractional amount", "The SEC must approve each individual trade"], "B",
        "AON offerings require the full issue to be sold within a specified period or the deal is voided.",
        ["all-or-none", "underwriting", "primary market"],
        "Identify all-or-none underwriting conditions",
        "Contrast AON with firm commitment and best efforts structures."))

    items.push(q(1, "market participants", "easy",
        "A broker-dealer acting as a broker in a transaction:",
        ["Buys securities for its own inventory", "Acts as agent, bringing together buyers and sellers for a commission", "Insures customer deposits", "Sets monetary policy"], "B",
        "Brokers act as agents facilitating trades; dealers act as principals buying and selling for their own account.",
        ["broker-dealer", "agent", "market participants"],
        "Distinguish broker (agent) from dealer (principal) roles",
        "Dealers profit from spreads; brokers earn commissions."))
    items.push(q(1, "market participants", "medium",
        "Market makers provide liquidity by:",
        ["Refusing to quote prices during volatility", "Quoting bid and ask prices at which they stand ready to buy or sell", "Only executing customer orders on other exchanges", "Filing SARs with FinCEN"], "B",
        "Market makers continuously quote prices and trade from inventory, narrowing spreads and improving liquidity.",
        ["market maker", "bid-ask spread", "liquidity"],
        "Explain market maker role in providing liquidity",
        "Market makers earn the spread but bear inventory risk."))
    items.push(q(1, "market participants", "medium",
        "Investment advisers are primarily regulated under the:",
        ["Securities Exchange Act of 1934 by the MSRB", "Investment Advisers Act of 1940 by the SEC or states", "Bank Secrecy Act by the FDIC", "Internal Revenue Code by FINRA"], "B",
        "Advisers managing client assets register with the SEC or state regulators depending on assets under management.",
        ["investment adviser", "Investment Advisers Act", "market participants"],
        "Identify regulatory framework for investment advisers",
        "Advisers have fiduciary duty; broker-dealers historically had suitability standard (Reg BI now applies)."))
    items.push(q(1, "market participants", "hard",
        "A transfer agent's primary function is to:",
        ["Underwrite new municipal bond issues", "Maintain records of security ownership and process transfers", "Conduct FINRA arbitration hearings", "Set margin requirements for customer accounts"], "B",
        "Transfer agents maintain shareholder records, issue certificates, and handle name changes and transfers.",
        ["transfer agent", "market participants", "shareholder records"],
        "Define transfer agent responsibilities",
        "Distinguish transfer agents from clearing firms and custodians."))
    items.push(q(1, "market participants", "easy",
        "Clearing corporations in the securities industry primarily:",
        ["Register new representatives on Form U4", "Facilitate settlement by confirming, netting, and guaranteeing trades", "Issue monetary policy directives", "Approve retail advertising materials"], "B",
        "Clearing firms (e.g., NSCC, DTCC) ensure trades settle properly and manage counterparty risk.",
        ["clearing", "settlement", "market participants"],
        "Understand clearing corporation role in trade settlement",
        "Clearing is distinct from trading execution and custody."))

    items.push(q(1, "economic factors", "medium",
        "Which is classified as a leading economic indicator?",
        ["Unemployment rate", "Average duration of unemployment", "Building permits for new private housing", "Gross domestic product (trailing quarter)"], "C",
        "Building permits tend to change before broader economic activity, signaling future construction and employment trends.",
        ["leading indicators", "economic factors", "building permits"],
        "Classify leading, coincident, and lagging economic indicators",
        "Leading: permits, stock prices; Lagging: unemployment, CPI changes."))
    items.push(q(1, "economic factors", "easy",
        "Gross Domestic Product (GDP) measures:",
        ["The total market value of goods and services produced within a country", "Only exports minus imports", "Corporate profits of S&P 500 companies", "The federal budget deficit"], "A",
        "GDP is the broadest measure of a nation's economic output over a specific period.",
        ["GDP", "economic factors", "macroeconomics"],
        "Define GDP and its significance",
        "Rising GDP generally signals economic expansion; declining GDP may indicate recession."))
    items.push(q(1, "economic factors", "medium",
        "The Consumer Price Index (CPI) is most directly used to measure:",
        ["Stock market volatility", "Inflation affecting consumer purchasing power", "Corporate bond default rates", "Margin account balances"], "B",
        "CPI tracks price changes in a basket of consumer goods and services, reflecting inflation trends.",
        ["CPI", "inflation", "economic factors"],
        "Understand CPI as an inflation gauge",
        "CPI also feeds into TIPS principal adjustments and COLA calculations."))
    items.push(q(1, "monetary policy", "medium",
        "The Federal Reserve's open market operations involve:",
        ["Buying or selling U.S. government securities to influence money supply and interest rates", "Setting corporate income tax rates", "Registering broker-dealers with FINRA", "Approving municipal official statements"], "A",
        "The Fed buys securities to inject liquidity (lower rates) and sells to drain liquidity (raise rates).",
        ["open market operations", "Federal Reserve", "monetary policy"],
        "Describe Fed open market operations",
        "Open market operations are the Fed's primary tool for targeting the federal funds rate."))
    items.push(q(1, "monetary policy", "hard",
        "When the Federal Reserve raises the discount rate, the likely market effect is:",
        ["Short-term interest rates tend to rise", "Bond prices tend to rise sharply", "The money supply tends to expand rapidly", "Stock dividends are automatically increased"], "A",
        "A higher discount rate makes borrowing from the Fed more expensive for banks, typically tightening monetary conditions and pushing rates up.",
        ["discount rate", "monetary policy", "interest rates"],
        "Predict effects of discount rate changes",
        "Review the three traditional Fed tools: OMO, discount rate, reserve requirements."))
    items.push(q(1, "monetary policy", "medium",
        "Quantitative easing (QE) refers to the Fed:",
        ["Eliminating all bank reserve requirements", "Purchasing large quantities of long-term securities to lower long-term interest rates", "Reducing the federal deficit through spending cuts", "Regulating municipal securities dealers"], "B",
        "QE expands the Fed's balance sheet through large-scale asset purchases when conventional rate cuts are insufficient.",
        ["quantitative easing", "monetary policy", "Federal Reserve"],
        "Define quantitative easing and its purpose",
        "QE is an unconventional tool used when short-term rates are near zero."))
    items.push(q(1, "fiscal policy", "easy",
        "Fiscal policy is implemented primarily through:",
        ["Federal Reserve open market operations", "Government taxation and spending decisions", "FINRA rule amendments", "MSRB continuing disclosure rules"], "B",
        "Congress and the executive branch set fiscal policy via budget, taxes, and government spending programs.",
        ["fiscal policy", "government spending", "taxation"],
        "Distinguish fiscal policy from monetary policy",
        "Monetary = Fed; Fiscal = elected government branches."))
    items.push(q(1, "fiscal policy", "medium",
        "An expansionary fiscal policy during a recession might include:",
        ["Raising taxes and cutting government spending", "Lowering taxes and increasing government spending", "Selling Treasury securities through the Fed", "Increasing bank reserve requirements"], "B",
        "Tax cuts and increased spending inject demand into the economy, countering recessionary pressures.",
        ["expansionary fiscal policy", "fiscal policy", "economic stimulus"],
        "Identify expansionary vs contractionary fiscal measures",
        "Expansionary fiscal policy can widen deficits but may boost economic activity."))

    items.push(q(1, "investment risks", "medium",
        "Systematic (market) risk affects:",
        ["Only one company in a diversified portfolio", "The entire market or economy and cannot be diversified away", "Only municipal bondholders", "Only investors using margin accounts"], "B",
        "Market risk—recessions, interest rate shifts, geopolitical events—impacts broad asset classes regardless of diversification.",
        ["systematic risk", "market risk", "diversification"],
        "Define systematic vs unsystematic risk",
        "Beta measures a stock's sensitivity to systematic market risk."))
    items.push(q(1, "investment risks", "easy",
        "Diversification is most effective at reducing:",
        ["Systematic risk from economic recessions", "Unsystematic (company-specific) risk", "Inflation risk for all asset classes equally", "All forms of investment risk completely"], "B",
        "Holding multiple uncorrelated securities reduces exposure to any single issuer's failure but not broad market downturns.",
        ["diversification", "unsystematic risk", "portfolio risk"],
        "Explain diversification benefits and limitations",
        "A portfolio of 15-20 stocks across sectors reduces company-specific risk significantly."))
    items.push(q(1, "investment risks", "medium",
        "Purchasing power risk is of greatest concern to investors holding:",
        ["Long-term fixed-rate bonds during periods of rising inflation", "Short-term T-bills in stable inflation", "Diversified large-cap equity portfolios only", "FDIC-insured bank CDs with variable rates tied to CPI"], "A",
        "Fixed income returns erode in real terms when inflation rises faster than coupon payments.",
        ["purchasing power risk", "inflation risk", "investment risks"],
        "Match inflation/purchasing power risk to asset types",
        "TIPS and variable-rate instruments help mitigate purchasing power risk."))
    items.push(q(1, "investment risks", "hard",
        "Reinvestment risk is greatest for an investor who:",
        ["Holds a zero-coupon bond to maturity", "Receives periodic coupon payments during a period of falling interest rates", "Owns a diversified portfolio of 50 stocks", "Holds a variable-rate preferred stock"], "B",
        "Coupon payments reinvested at lower rates during a declining rate environment reduce total return.",
        ["reinvestment risk", "interest rates", "investment risks"],
        "Identify when reinvestment risk is most significant",
        "Callable bonds also expose holders to reinvestment risk when called in low-rate environments."))
    items.push(q(1, "yield and bond price relationship", "hard",
        "A 4% coupon bond purchased at par sees market rates rise to 6%. The bond will most likely trade:",
        ["At a premium", "At par", "At a discount", "At a price unaffected by rate changes"], "C",
        "When prevailing rates exceed the coupon, existing bonds must sell below par to offer competitive yields.",
        ["discount bond", "interest rate risk", "yield and bond price relationship"],
        "Predict bond price direction when rates change",
        "Draw a simple diagram: rates up → prices down; rates down → prices up."))
    items.push(q(1, "yield and bond price relationship", "medium",
        "If a bond's yield to maturity (YTM) is greater than its coupon rate, the bond is trading:",
        ["At a premium", "At par", "At a discount", "At a price that cannot be determined"], "C",
        "Discount bonds must offer yields above the stated coupon to compensate investors for below-par purchase prices.",
        ["yield to maturity", "discount bond", "yield and bond price relationship"],
        "Relate YTM, coupon rate, and premium/discount status",
        "Premium: YTM < coupon; Discount: YTM > coupon; Par: YTM = coupon."))
    items.push(q(1, "yield and bond price relationship", "medium",
        "Duration is best described as a measure of a bond's:",
        ["Credit rating stability", "Price sensitivity to interest rate changes", "Liquidity in the secondary market", "Tax status for municipal investors"], "B",
        "Higher duration means greater percentage price change for a given interest rate movement.",
        ["duration", "interest rate sensitivity", "yield and bond price relationship"],
        "Define duration and its practical meaning",
        "Longer maturity and lower coupons generally increase duration."))
    items.push(q(1, "market participants", "medium",
        "The Securities Investor Protection Corporation (SIPC) primarily protects customers if:",
        ["A broker-dealer fails financially and customer securities or cash are missing from their accounts",
         "Any stock declines in value due to market conditions", "The SEC delays an IPO registration",
         "A customer files a complaint about commissions"], "A",
        "SIPC covers missing customer assets when a member firm fails, up to statutory limits—not market losses.",
        ["SIPC", "customer protection", "market participants"],
        "Distinguish SIPC protection from FDIC and market risk",
        "SIPC does not insure against a decline in the value of your securities."))
    items.push(q(1, "secondary market", "medium",
        "The third market refers to trading of:",
        ["Newly issued securities directly from the issuer", "Exchange-listed securities in the OTC market away from the exchange floor",
         "Municipal bonds only in the primary market", "Foreign currencies on the interbank market"], "B",
        "Third-market trading involves listed securities executed OTC, often by institutional participants.",
        ["third market", "secondary market", "OTC"],
        "Define third and fourth market concepts tested on the SIE",
        "Fourth market = direct institution-to-institution trading without broker involvement."))

    return items;
}

export const questions = section1_questions();
